# Cấu hình huấn luyện ResNet50 cho Action Multi-label Classification

# Thư mục chứa kết quả train (weights, logs, visualizations)
output_dir: "/home/laptq/classification_multilabel/outputs/train/v21.efficientnetv2.cluster-CNN-8--cut-l4.remove-tkcsp-ctvgxh"

resume_path: null # Path tới thư mục run để resume (nếu có)

# Thứ tự các class (Quan trọng: phải khớp với chỉ số khi lưu/load model)
classes:
  - "cho_tay_vao_tui_quan"
  - "cho_tay_vao_tui_ao"
  - "cho_tay_vao_tui_deo_tren_nguoi"
  - "cho_tay_vao_tui_cam_tren_tay"
  # - "cho_tay_vao_gio_xe_hang"
  - "cho_tay_vao_ke"
  - "tay_cam_san_pham"
  # - "tay_khong_cam_san_pham"

# Dữ liệu tập Train (Danh sách file .txt)
train_data:
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_quan/train--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_ao/train--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_deo_tren_nguoi/train--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_cam_tren_tay/train--min4k--max5k.txt"
  # - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_gio_xe_hang/train--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_ke/train--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/tay_cam_san_pham/train--min4k--max5k.txt"
  # - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/tay_khong_cam_san_pham/train--min4k--max5k.txt"

# Dữ liệu tập Val/Test (Danh sách file .txt)
val_data:
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_quan/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_ao/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_deo_tren_nguoi/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_cam_tren_tay/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_gio_xe_hang/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_ke/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/tay_cam_san_pham/val--min4k--max5k.txt"
  - "/home/laptq/data/processed/fs26/train_data/classify_rgb_multilabel/labels_actions--cluster-CNN-8--cut-l4/tay_khong_cam_san_pham/val--min4k--max5k.txt"

# Tham số Training
epochs: 50
batch_size: 64
lr: 1e-5
weight_decay: 0.0005
patience: 30
num_workers: 4
precision: 32 # Có thể dùng 16 hoặc 32

accelerator: "gpu" # "cpu", "gpu"
devices: [0] # "auto", 0, 1, ...

model: "efficientnetv2s"

train_augment:
  - SquarePad: {}
  - RandomHorizontalFlip: {}
  - RandAugment:
      num_ops: 4
      magnitude: 9
      interpolation: "BILINEAR"
  - Downscale:
      scale_range: [0.5, 0.5]
      p: 0.1
  - ChannelShuffle:
      p: 0.5
  # - GaussNoise:
  #     p: 0.1
  - ColorJitter:
      hue: 0.15
  - RandomGrayscale:
      p: 0.1
  # - Resize:
  #     size: [224, 224]
  - RandomResizedCrop:
      size: [224, 224]
      scale: [0.7, 1.0]
  - ToTensor: {}
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_augment:
  - SquarePad: {}
  - Resize:
      size: [224, 224]
  - ToTensor: {}
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
