# Cấu hình huấn luyện EfficientNetV2 cho Multi-label Classification

# Thư mục chứa kết quả train (weights, logs, visualizations)
output_dir: "/home/laptq/laptq-fs26-shoplifting-detection/runs/classification_multilabel/v1.efficientnetv2s.rap2+cia+cia_gen"

resume_path: null # Path tới thư mục run để resume (nếu có)

# Danh sách các class
classes:
  - "backpack"      # 0
  - "basket"        # 1
  - "box"           # 2
  - "cart"          # 3
  - "handbag"       # 4
  - "handtrunk"     # 5
  - "other"         # 6
  - "paperbag"      # 7
  - "plasticbag"    # 8
  - "product"       # 9
  - "shoulderbag"    # 10

# Dữ liệu tập Train (Danh sách file .txt)
train_data:
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/CIA_combined_with_geneated_editting.txt"
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/CIA_original.txt"
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/RAP2_test.txt"
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/RAP2_train.txt"
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/RAP2_val.txt"

# Dữ liệu tập Val/Test (Danh sách file .txt)
val_data:
  - "/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb_multilabel/Satudora_test.txt"

# Tham số Training
epochs: 30
batch_size: 64
lr: 1e-4
weight_decay: 1e-5
patience: 10
num_workers: 4
precision: 32

accelerator: "gpu"
devices: [1, 2] # Sử dụng GPU 0 (hoặc thay đổi cho phù hợp với hệ thống)
