# Cấu hình huấn luyện EfficientNetV2 cho Multi-label Classification

# Thư mục chứa kết quả train (weights, logs, visualizations)
output_dir: "/home/laptq/classification_multilabel/outputs/train/v2.resnet50.rap2+cia+cia_gen.change_class_order"

model: "resnet50"

resume_path: null # Path tới thư mục run để resume (nếu có)

# Danh sách các class
classes:
  - "backpack"      # 0
  - "shoulderbag"   # 1
  - "handbag"       # 2
  - "box"           # 3
  - "plasticbag"    # 4
  - "paperbag"      # 5
  - "handtrunk"     # 6
  - "other"         # 7
  - "basket"        # 8
  - "cart"          # 9
  - "product"       # 10

# Dữ liệu tập Train (Danh sách file .txt)
train_data:
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/CIA_combined_with_geneated_editting.txt"
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/CIA_original.txt"
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/RAP2_test.txt"
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/RAP2_train.txt"
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/RAP2_val.txt"

# Dữ liệu tập Val/Test (Danh sách file .txt)
val_data:
  - "/home/laptq/data/fs26/processed/train_data/classify_rgb_multilabel/person_attributes/Satudora_test.txt"

# Tham số Training
epochs: 50
batch_size: 128
lr: 1e-4
weight_decay: 1e-5
patience: 20
num_workers: 8
precision: 32

accelerator: "gpu"
devices: [1, 2] # Sử dụng GPU 0 (hoặc thay đổi cho phù hợp với hệ thống)

train_augment:
  # - SquarePad: {}
  - RandomHorizontalFlip: {}
  - RandAugment:
      num_ops: 4
      magnitude: 9
      interpolation: "BILINEAR"
  - Downscale:
      scale_range: [0.5, 0.5]
      p: 0.1
  - ChannelShuffle:
      p: 0.5
  # - GaussNoise:
  #     p: 0.1
  - ColorJitter:
      hue: 0.15
  - RandomGrayscale:
      p: 0.1
  - Resize:
      size: [256, 192]
  # - RandomResizedCrop:
  #     size: [224, 224]
  #     scale: [0.7, 1.0]
  - ToTensor: {}
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_augment:
  # - SquarePad: {}
  - Resize:
      size: [256, 192]
  - ToTensor: {}
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
